### ISSUE TITLE
可否 视频流服务器 web页面 将 electron的 左侧边栏也挂上来

### ISSUE THREAD

**Issue by leeboyka** [congzhen/cm_file_collectors#15]
可否 视频流服务器 web页面 将 electron的 左侧边栏也挂上来 ； 希望 web页面 也能像 桌面程序 那样布局，把展示和筛选功能弄上来

**Comment by congzhen** [comment]
左上角的按钮
















在 2024-09-28 15:07:10，"李妄一" ***@***.***> 写道：

可否 视频流服务器 web页面 将 electron的 左侧边栏也挂上来 ； 希望 web页面 也能像 桌面程序 那样布局，把展示和筛选功能弄上来

**Comment by leeboyka** [comment]
左上角按钮弹出的drawer里只有演员， 貌似没有其他？

**Comment by congzhen** [comment]
放大镜那个按钮不能点击吗？
















在 2024-09-29 03:09:25，"李妄一" ***@***.***> 写道：

左上角按钮弹出的drawer里只有演员， 貌似没有其他？

**Comment by leeboyka** [comment]
我傻逼
